services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpassword"
      POSTGRES_DB: "pguserdb"
    ports:
      - "5432:5432"

volumes:
  db:
    driver: local
